## Working with Complex Numbers in Python


This notebook demonstrates how to work with complex numbers in Python using both the `cmath` module and NumPy.

In [1]:
import cmath
import numpy as np

---
### 1. Creating Complex Numbers

In Python, complex numbers use `j` to represent the imaginary unit (instead of `i`).

In [2]:
x = 4+3j
type(x)

complex

#### Variable Name Note

Be careful: `j` can be used as a regular variable name. Python only treats `j` as imaginary when it appears immediately after a number.

In [3]:
j = 7
print(j)
type(j)

7


int

#### Using Complex Numbers in Loops

In [4]:
for j in range(0,10):
    x = j+1j
    print(x)

1j
(1+1j)
(2+1j)
(3+1j)
(4+1j)
(5+1j)
(6+1j)
(7+1j)
(8+1j)
(9+1j)


---
### 2. Basic Complex Arithmetic

In [5]:
print(x)
print(x**2)
print(1j**2)  # Should be -1

(9+1j)
(80+18j)
(-1+0j)


---
### 3. Accessing Real and Imaginary Parts

In [6]:
x.real

9.0

In [7]:
print(x, x.real, x.imag)

(9+1j) 9.0 1.0


---
### 4. Polar Form Using `cmath`
Convert from Cartesian $(a + bi)$ to polar form $(r, \theta)$ where:
- $r = |z| = \sqrt{a^2 + b^2}$ (magnitude)
- $\theta = \arg(z) $ (phase angle in radians)

In [8]:
cmath.polar(x)  # Returns (magnitude, phase)

(9.055385138137417, 0.11065722117389565)

---
### 5. Complex Exponential Function

The complex exponential: $e^{a+bi} = e^a(\cos b + i\sin b)$

In [9]:
cmath.exp(x)

(4378.114930712042+6818.510012517896j)

#### Euler's Formula: $e^{i\pi} = -1$

In [10]:
cmath.exp(0+cmath.pi*1j)  # Should equal -1 (with small numerical error)

(-1+1.2246467991473532e-16j)

#### Using a real variable (j=9 from earlier loop)

In [11]:
cmath.exp(0+cmath.pi*j)  # j is now 9, so this is e^(9π)

(1902773895292.1592+0j)

---
### 6. Complex Arrays with NumPy

NumPy provides efficient operations on arrays of complex numbers.

In [12]:
a = np.array([1+2j, 3+4j, 5+6j])

#### Extract Real Parts

In [13]:
np.real(a)

array([1., 3., 5.])

#### Extract Imaginary Parts

In [14]:
np.imag(a)

array([2., 4., 6.])

#### Complex Conjugate

For $z = a + bi$, the conjugate is $\bar{z} = a - bi$

In [15]:
np.conj(a)

array([1.-2.j, 3.-4.j, 5.-6.j])

---
### 7. Creating Complex Arrays

Use `dtype='complex'` to create arrays that can store complex numbers.

In [16]:
a = np.zeros((3,3), dtype='complex')
print(a)

[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]


In [17]:
a[0,0] = 1+3j

---
### 8. Phase Angle (Argument)

Get the angle $\theta$ in the complex plane.

In [18]:
np.angle([1.0, 1.0j, 1+1j], deg=True)  # Angles in degrees

array([ 0., 90., 45.])

---
### 9. Magnitude (Absolute Value)

Compute $|z| = \sqrt{a^2 + b^2}$ for complex number $z = a + bi$

In [19]:
np.absolute([1.0, 1.0j, 1+1j])

array([1.        , 1.        , 1.41421356])

---
### 10. Data Types

NumPy uses `complex128` (double precision) for complex numbers.

In [20]:
type(a[0,0])

numpy.complex128

---
## Summary

**Key functions for complex numbers:**

| Operation | Python `cmath` | NumPy |
|-----------|----------------|-------|
| Create | `z = 3+4j` | `np.array([3+4j])` |
| Real part | `z.real` | `np.real(z)` |
| Imaginary part | `z.imag` | `np.imag(z)` |
| Magnitude | `abs(z)` | `np.absolute(z)` |
| Phase | `cmath.phase(z)` | `np.angle(z)` |
| Polar form | `cmath.polar(z)` | — |
| Conjugate | `z.conjugate()` | `np.conj(z)` |
| Exponential | `cmath.exp(z)` | `np.exp(z)` |

**Important notes:**
- Python uses `j` (not `i`) for the imaginary unit
- Use `dtype='complex'` when creating NumPy arrays for complex numbers
- NumPy functions work element-wise on arrays