# Lecture 6b: Linear Algebra with NumPy and SciPy

**Solving systems of linear equations computationally**

---

## Introduction to Linear Systems

Linear algebra is fundamental to scientific computing, data science, and machine learning. Python provides powerful tools through NumPy and SciPy to solve systems of linear equations efficiently.

A system of linear equations can be written in matrix form as: **Ax = b**

Where:
- **A** is the coefficient matrix
- **x** is the vector of unknowns
- **b** is the constant vector

## Step 1: Import Linear Algebra Libraries

We'll use both NumPy and SciPy's linear algebra modules:

In [1]:
import numpy.linalg as np_linalg
import scipy.linalg as sp_linalg
import numpy as np

**Why import separately?** Both NumPy and SciPy have `linalg` modules. Using explicit imports prevents naming conflicts and makes it clear which library you're using.

## Step 2: Define the Problem

Let's solve this system of three equations with three unknowns:

```
1x + 2y - 1z = 3
2x - 1y + 1z = 1
1x + 1y + 1z = 6
```

We can represent this system as matrices:

In [2]:
# Define coefficient matrix A
A = np.array([
    [1, 2, -1],
    [2, -1, 1],
    [1, 1, 1],
])

# Define constant vector b
b = np.array([3, 1, 6])

print("Shape of A:", A.shape)
print("Shape of b:", b.shape)
print("\nMatrix A:")
print(A)
print("\nVector b:")
print(b)

Shape of A: (3, 3)
Shape of b: (3,)

Matrix A:
[[ 1  2 -1]
 [ 2 -1  1]
 [ 1  1  1]]

Vector b:
[3 1 6]


## Step 3: Display Equations (Optional)

We can programmatically display the equations in readable format:

In [3]:
# Display equations in readable format
print("System of equations:")
print("-" * 40)
for i in range(A.shape[0]):
    terms = []
    for j in range(A.shape[1]):
        terms.append("{1} x[{0}]".format(j, A[i, j]))
    print(" + ".join(terms), "=", b[i])

print("\nNote: x[0] = x, x[1] = y, x[2] = z")

System of equations:
----------------------------------------
1 x[0] + 2 x[1] + -1 x[2] = 3
2 x[0] + -1 x[1] + 1 x[2] = 1
1 x[0] + 1 x[1] + 1 x[2] = 6

Note: x[0] = x, x[1] = y, x[2] = z


## Step 4: Solve with NumPy

NumPy provides a direct solver for linear systems:

In [4]:
# Solve using NumPy
x = np_linalg.solve(A, b)

print("Solution using NumPy:")
print("x = {:.2f}, y = {:.2f}, z = {:.2f}".format(x[0], x[1], x[2]))
print("\nSolution vector:", x)

Solution using NumPy:
x = 0.43, y = 2.71, z = 2.86

Solution vector: [0.42857143 2.71428571 2.85714286]


## Step 5: Verify the Solution

We can verify our solution by checking if **Ax - b ≈ 0**:

In [5]:
# Verify: Ax - b should equal [0, 0, 0]
verification = np.dot(A, x) - b

print("Verification (Ax - b):")
print(verification)
print("\n✓ If all values are zero (or very close to zero), the solution is correct!")

Verification (Ax - b):
[ 0.0000000e+00  0.0000000e+00 -8.8817842e-16]

✓ If all values are zero (or very close to zero), the solution is correct!


## Alternative Solution Methods

### Method 1: Matrix Inverse (Less Efficient)

In [6]:
# Using SciPy to invert matrix A and multiply by b
xnew = sp_linalg.inv(A).dot(b)

print("Solution using matrix inverse:")
print("x = {:.2f}, y = {:.2f}, z = {:.2f}".format(xnew[0], xnew[1], xnew[2]))

Solution using matrix inverse:
x = 0.43, y = 2.71, z = 2.86


**Note:** Computing the inverse is computationally expensive and less numerically stable than using a direct solver.

### Method 2: SciPy Solver (Recommended)

In [7]:
# Using SciPy's direct solver (more efficient)
xnew = sp_linalg.solve(A, b)

print("Solution using SciPy solver:")
print("x = {:.2f}, y = {:.2f}, z = {:.2f}".format(xnew[0], xnew[1], xnew[2]))

Solution using SciPy solver:
x = 0.43, y = 2.71, z = 2.86


**✓ Best Practice:** Use `solve()` instead of inverting the matrix for better performance and numerical stability.

## Complete Example: Putting It All Together

In [8]:
# Complete workflow
import numpy as np
import numpy.linalg as np_linalg

# Define the problem
A = np.array([
    [1, 2, -1],
    [2, -1, 1],
    [1, 1, 1],
])
b = np.array([3, 1, 6])

# Solve
x = np_linalg.solve(A, b)

# Display results
print("="*50)
print("SOLUTION")
print("="*50)
print(f"x = {x[0]:.4f}")
print(f"y = {x[1]:.4f}")
print(f"z = {x[2]:.4f}")
print("="*50)

# Verify
residual = np.linalg.norm(np.dot(A, x) - b)
print(f"\nResidual (should be ~0): {residual:.2e}")

SOLUTION
x = 0.4286
y = 2.7143
z = 2.8571

Residual (should be ~0): 8.88e-16


## Summary

✓ Linear systems **Ax = b** can be solved efficiently with Python

✓ Use `np.linalg.solve(A, b)` or `sp.linalg.solve(A, b)` for direct solving

✓ Avoid matrix inversion when possible - use `solve()` instead

✓ Always verify your solution by checking **Ax - b ≈ 0**

✓ Import linear algebra modules explicitly to avoid naming conflicts

---

## Practice Exercises

1. Try solving a 4x4 system of equations
2. Compare the performance of NumPy vs SciPy solvers using `%timeit`
3. Explore eigenvalue problems using `np.linalg.eig()`
4. Investigate singular matrices and what happens when they can't be solved