# Introduction to NumPy Broadcasting

## What is Broadcasting?
Broadcasting is NumPy's way of performing operations on arrays that have different shapes. Think of it as NumPy's "smart" way of making arrays work together, even when they're different sizes.

## Basic Example: Same Shapes
When arrays have the same shape, operations work element by element:

In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])     # Shape: (4,)
b = np.array([10, 20, 30, 40]) # Shape: (4,)
result = a * b                 # Multiply each pair: 1×10, 2×20, 3×30, 4×40
print("a =", a)
print("b =", b)
print("a * b =", result)

a = [1 2 3 4]
b = [10 20 30 40]
a * b = [ 10  40  90 160]


## Broadcasting with Different Shapes

### Example 1: Array + Single Number

In [2]:
a = np.array([1, 2, 3])
result = a + 10        # Adds 10 to each element
print("a =", a)
print("a + 10 =", result)
print("NumPy automatically 'broadcasts' the single number 10 to match the array shape!")

a = [1 2 3]
a + 10 = [11 12 13]
NumPy automatically 'broadcasts' the single number 10 to match the array shape!


### Example 2: When Shapes Don't Match

In [3]:
a = np.array([1, 2, 3])    # Shape: (3,)
b = np.array([10, 20])     # Shape: (2,)

print("a shape:", a.shape)
print("b shape:", b.shape)
print("These shapes are incompatible for broadcasting!")

# Uncomment the line below to see the error:
#result = a + b  # Would give an error

a shape: (3,)
b shape: (2,)
These shapes are incompatible for broadcasting!


### Example 3: Making Shapes Compatible
We can reshape arrays to make broadcasting work:

In [4]:
a = np.array([1, 2, 3])           # Shape: (3,)
b = np.array([10, 20])            # Shape: (2,)

# Reshape 'a' to be a column (3×1)
a_column = a[:, np.newaxis]       # Shape: (3, 1)

print("Original a shape:", a.shape)
print("Reshaped a_column shape:", a_column.shape)
print("b shape:", b.shape)
print()

result = a_column + b             # Broadcasting works now!
print("a_column + b =")
print(result)
print()
print("Explanation:")
print("Row 1: 1 + [10, 20] = [11, 21]")
print("Row 2: 2 + [10, 20] = [12, 22]")
print("Row 3: 3 + [10, 20] = [13, 23]")

Original a shape: (3,)
Reshaped a_column shape: (3, 1)
b shape: (2,)

a_column + b =
[[11 21]
 [12 22]
 [13 23]]

Explanation:
Row 1: 1 + [10, 20] = [11, 21]
Row 2: 2 + [10, 20] = [12, 22]
Row 3: 3 + [10, 20] = [13, 23]


## Understanding Array Shapes

### Creating Different Shapes

In [5]:
arr = np.array([1, 2, 3])         # 1D array, shape: (3,)

# Make it a column vector (3 rows, 1 column)
column = arr[:, np.newaxis]       # Shape: (3, 1)

# Make it a row vector (1 row, 3 columns)  
row = arr[np.newaxis, :]          # Shape: (1, 3)

print("Original array:")
print(arr)
print("Shape:", arr.shape)
print()

print("Column vector:")
print(column)
print("Shape:", column.shape)
print()

print("Row vector:")
print(row)
print("Shape:", row.shape)

Original array:
[1 2 3]
Shape: (3,)

Column vector:
[[1]
 [2]
 [3]]
Shape: (3, 1)

Row vector:
[[1 2 3]]
Shape: (1, 3)


## Practical Example
Matrix + row vector (broadcasting happens automatically!)

In [6]:
# Matrix + row vector
matrix = np.array([[1, 2],        # Shape: (3, 2)
                   [3, 4],
                   [5, 6]])

row_to_add = np.array([10, 20])   # Shape: (2,)

print("Matrix:")
print(matrix)
print("Matrix shape:", matrix.shape)
print()

print("Row to add:", row_to_add)
print("Row shape:", row_to_add.shape)
print()

result = matrix + row_to_add      # Broadcasting works automatically!
print("Matrix + Row:")
print(result)
print()
print("What happened:")
print("Row 1: [1,2] + [10,20] = [11,22]")
print("Row 2: [3,4] + [10,20] = [13,24]")
print("Row 3: [5,6] + [10,20] = [15,26]")

Matrix:
[[1 2]
 [3 4]
 [5 6]]
Matrix shape: (3, 2)

Row to add: [10 20]
Row shape: (2,)

Matrix + Row:
[[11 22]
 [13 24]
 [15 26]]

What happened:
Row 1: [1,2] + [10,20] = [11,22]
Row 2: [3,4] + [10,20] = [13,24]
Row 3: [5,6] + [10,20] = [15,26]


## Key Rules for Broadcasting
1. **Same shapes**: Operations work element by element
2. **Different shapes**: NumPy tries to "stretch" the smaller array
3. **Incompatible shapes**: Use `np.newaxis` to add dimensions
4. **Scalars always work**: Single numbers broadcast to any array shape

## Tips
- [:, np.newaxis] makes a column vector (adds dimension on the right)
- [np.newaxis, :] makes a row vector (adds dimension on the left)
- Think of broadcasting as copying values to make arrays the same size
- Start with simple examples and build up to more complex ones

## Common Mistake to Avoid

In [7]:
# This won't work:
a = np.array([1, 2, 3])     # Shape: (3,)
b = np.array([10, 20])      # Shape: (2,)
print("This would cause an error:")
print("a + b when a.shape =", a.shape, "and b.shape =", b.shape)
print()

# This will work:
result = a[:, np.newaxis] + b  # Makes a into shape (3,1), broadcasts to (3,2)
print("This works:")
print("a[:, np.newaxis] + b =")
print(result)
print("Shape of result:", result.shape)

This would cause an error:
a + b when a.shape = (3,) and b.shape = (2,)

This works:
a[:, np.newaxis] + b =
[[11 21]
 [12 22]
 [13 23]]
Shape of result: (3, 2)


---
## Brief Introduction to Numerical Integration with TRAPZ

In [8]:
import numpy as np
x = np.arange(0, 10)  # Creating an array of x values from 0 to 9
y = x**2  # Computing y as the square of x (y = x^2)
int_result = np.trapz(y, x)  # Using the trapezoidal rule to integrate y with respect to x
print('int_result=', int_result) # Printing the integral
print('10**3/3=', 10**3/3) # Printing the analytical solution

int_result= 244.5
10**3/3= 333.3333333333333


In [9]:
# Using more points for better accuracy
x = np.linspace(0, 10, 100)  # Creating 100 evenly spaced x values from 0 to 10
y = x**2  # Recomputing y as the square of x
int_result = np.trapz(y, x)  # Performing trapezoidal integration again
print('int_result=', int_result) # Printing the integral
print('10**3/3=', 10**3/3) # Printing the analytical solution

int_result= 333.35033840084344
10**3/3= 333.3333333333333
